### PR TITLE
tune-sklearn v0.4.6

### PR DESCRIPTION
**Pull request by DManowitz**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

#9

### CODE REVIEW

**Comment by DManowitz** [comment]
@conda-forge-admin please rerender

**Comment by hadim** [comment]
LGTM. Do you want to add yourself as a maintainer in the "recipe-maintainers" section?

**Comment by DManowitz** [comment]
Sure

**Comment by hadim** [comment]
> LGTM. Do you want to add yourself as a maintainer in the "recipe-maintainers" section?

You need to add your name in the relevant section in the recipe file of this PR. Once done I can merge here.

**Comment by DManowitz** [comment]
> > LGTM. Do you want to add yourself as a maintainer in the "recipe-maintainers" section?
> 
> You need to add your name in the relevant section in the recipe file of this PR. Once done I can merge here.

Done

**Pull request merged**
